[build]
  command = "pnpm build"
  publish = "website/build"

[build.environment]
  NODE_VERSION = "14"

[context.production]
  command = "pnpm netlify:build:production"

[context.deploy-preview]
  command = "pnpm netlify:build:deployPreview"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    "node_modules/.cache/webpack",
  ]