  name: Verdaccio Website CI

  on:
    workflow_dispatch:
    push:
      paths:
        - "website/**"
        - "package.json"

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.1

        - name: Use Node 14
          uses: actions/setup-node@v2
          with:
            node-version: 14

        - name: Install pnpm
          run: npm i pnpm@latest -g

        - name: Set store
          run: |
            mkdir ~/.pnpm-store
            pnpm config set store-dir ~/.pnpm-store

        - name: Install
          run: pnpm recursive install --frozen-lockfile --ignore-scripts

        - name: Cache .pnpm-store
          uses: actions/cache@v2
          with:
            path: ~/.pnpm-store
            key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
            restore-keys: |
              pnpm-

        - name: Lint And Pretty
          run: |
            pnpm eslint:check --filter ...@verdaccio/website
            pnpm prettier:check --filter ...@verdaccio/website

        - name: Build Production
          if: github.ref == 'refs/heads/master'
          env:
            NETLIFY: true
            CONTEXT: production
          run: pnpm netlify:build:production --filter ...@verdaccio/website

        - name: Build Deployment Preview
          if: github.ref != 'refs/heads/master'
          env:
            NETLIFY: true
            CONTEXT: deploy-preview
          run: pnpm netlify:build:deployPreview --filter ...@verdaccio/website

        - name: Cache Docusaurus Build
          uses: actions/cache@v2
          with:
            path: |
              website/node_modules/.cache/webpack
            key: node_modules/.cache/webpack-${{github.ref}}
            restore-keys: |
              node_modules/.cache/webpack-${{github.ref}}
