  name: Verdaccio Website CI

  on:
    workflow_dispatch:
    push:
      # paths:
      #   - "website/**"
      #   - "package.json"

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.1

        - name: Use Node 14
          uses: actions/setup-node@v2
          with:
            node-version: 14

        - name: Cache pnpm modules
          uses: actions/cache@v2
          env:
            cache-name: cache-pnpm-modules
          with:
            path: ~/.pnpm-store
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.0.2
            run_install: |
              - recursive: true
                args: [--frozen-lockfile, --ignore-scripts]

        - name: Lint And Pretty
          run: |
            pnpm eslint:check --filter ...@verdaccio/website
            pnpm prettier:check --filter ...@verdaccio/website

        - name: Cache Docusaurus Build
          uses: actions/cache@v2
          with:
            path: website/node_modules/.cache/webpack
            key: cache/webpack-${{github.ref}}
            restore-keys: cache/webpack-${{github.ref}}

        - name: Build Production
          if: github.ref == 'refs/heads/master'
          env:
            NETLIFY: true
            CONTEXT: production
          run: pnpm netlify:build:production --filter ...@verdaccio/website

        - name: Build Deployment Preview
          if: github.ref != 'refs/heads/master'
          env:
            NETLIFY: true
            CONTEXT: deploy-preview
          run: pnpm netlify:build:deployPreview --filter ...@verdaccio/website

